---
title: "Data Mainpulation"
output: github_document
---

The file is for data import.


```{r}
library(tidyverse)
```

Load the litters and pups datasets

```{r}
litters_df <-
  read_csv(
    file = "data/FAS_litters.csv",
           na = c("","NA","."))

litters_df = janitor::clean_names(litters_df)

pups_df = 
  read_csv(
    file = "data/FAS_pups.csv",
    skip = 3,
    na = c("","NA","."))

pups_df = janitor::clean_names(pups_df)

```

##Select some variable

```{r}
select(litters_df, group,litter_number)

select((litters_df,group:gd_of_birth)
       
select(litters_df, -group)

select(litters_df, starts_with("gd"))

select(litters_df, starts_with("gd"),group)

select(litters_df,GROUP = group, everything())

select(litters_df, -starts_with("gd"))


```

a couple of alternatives

```{r}
rename(litters_df, GROUP = group)

relocate(litters_df, litter_number, gd0_weight)

```

In the pups data, select litter number, sex, and PD ears

```{r}
select(pups_df, litter_number, sex, pd_ears)
```

##'filter' some rows

```{r}

```

